### PR TITLE
fixed build failed on windows and checked running correctly.

### LINKED ISSUE #101: Building the application fails on Windows
When building the application on Windows, it fails on [this line](https://github.com/laravel-zero/framework/blob/stable/src/Commands/App/Builder.php#L104) because of path seperators.

```
***************************************
*     Building the application...     *
***************************************

Moving configuration to production mode...
Compiling code...

  InvalidArgumentException : RegexIterator::__construct(): No ending delimiter '#' found

  at E:\Code\GitHub\svenluijten\zero-test\vendor\laravel-zero\framework\src\Commands\App\Builder.php: 104
  100:             ->getCompiler($name);
  101:
  102:         $structure = config('app.structure') ?: $this->structure;
  103:
  104:         $compiler->buildFromDirectory(BASE_PATH, '#'.implode('|', $structure).'#');
  105:         $compiler->setStub(
  106:             "#!/usr/bin/env php \n".$compiler->createDefaultStub('bootstrap'.DIRECTORY_SEPARATOR.'init.php')
  107:         );
  108:
  109:         return $this;

  Exception trace:

  1   Phar::buildFromDirectory("E:\Code\GitHub\svenluijten\zero-test", "#app\|bootstrap\|vendor\|config\#")
      E:\Code\GitHub\svenluijten\zero-test\vendor\laravel-zero\framework\src\Commands\App\Builder.php : 104

  2   LaravelZero\Framework\Commands\App\Builder::compile("application")
      E:\Code\GitHub\svenluijten\zero-test\vendor\laravel-zero\framework\src\Commands\App\Builder.php : 78

  Please use the argument -v to see all trace.
```

After some debugging around that line and printing out the contents of `'#'.implode('|', $structure).'#'`, I found the issue: 

```php
$structure = config('app.structure') ?: $this->structure;

dd('#'.implode('|', $structure).'#');

$compiler->buildFromDirectory(BASE_PATH, str_replace('\\', '/', '#'.implode('|', $structure).'#'));
```

Results in this output: 

```
***************************************
*     Building the application...     *
***************************************

Moving configuration to production mode...
Compiling code...
string(33) "#app\|bootstrap\|vendor\|config\#"
```

As you can see, the last character of the regex is a path seperator, which so happens to be the same character used for escaping things! So in this case, the ending delimiter (`#`) is being escaped, resulting in a faulty regex.

This can be solved by escaping the escape-characters (escape-ception 😥) with `preg_quote()`: 

```php
$compiler->buildFromDirectory(BASE_PATH, preg_quote('#'.implode('|', $structure).'#'));
```

PR incoming 😉

### PR DESCRIPTION
**Pull request by lesstif**
this PR fixed #101 
thanks!

### CODE REVIEW

File: src/Commands/App/Builder.php [hunk 1]
```diff
@@ -100,8 +100,16 @@ protected function compile(string $name): Builder
             ->getCompiler($name);
 
         $structure = config('app.structure') ?: $this->structure;
+        
+        // See - https://github.com/laravel-zero/framework/pull/102
+        $regex = '#'.implode('|', $structure).'#';
 
-        $compiler->buildFromDirectory(BASE_PATH, '#'.implode('|', $structure).'#');
+        if (stristr(PHP_OS, "WINNT") != FALSE) {
```
Comment (svenluijten) [inline src/Commands/App/Builder.php]: Should use strict comparison here: `!==`. Otherwise it has the possibility of false positives in some edgecases.

File: src/Commands/App/Builder.php [hunk 2]
```diff
@@ -100,8 +100,16 @@ protected function compile(string $name): Builder
...
+            $compiler->buildFromDirectory(BASE_PATH, str_replace('\\', '/', $regex));
```
Comment (svenluijten) [inline src/Commands/App/Builder.php]: I think `preg_quote()` would be a better fit here, there might be some other unforeseen cases that won't be solved by just replacing `\` with `/`.

Comment (lesstif) [reply src/Commands/App/Builder.php]: i was pulled down your commit, it seems ok  but unfortunately compiled laravel zero application does't running on windows platform.

this PR is build and running correctly on windows. thanks

File: src/Commands/App/Builder.php (hunk 1 above)
Comment (lesstif) [reply src/Commands/App/Builder.php]: good point! thanks.

Comment (nunomaduro) [reply src/Commands/App/Builder.php]: @lesstif Can you fix it? I can do it for you if you want 🙂

Comment (lesstif) [reply src/Commands/App/Builder.php]: @nunomaduro i fixed it. thanks.
